In [1]:
import tensorflow as tf 
print('tensorflow version', tf.__version__)

tensorflow version 2.4.0


In [2]:
import numpy as np
import pandas as pd

# Introduction to TensorFlow

## Constants and Variables

Tensors are generalisations of vectors and matrices.

In [3]:
# 1D Tensor
print(tf.ones((1,)))

tf.Tensor([1.], shape=(1,), dtype=float32)


2021-10-29 09:04:18.935885: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
print(tf.ones((2,)))

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [5]:
# 2D Tensor
print(tf.ones((2,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [6]:
# 3D Tensor
print(tf.ones((2,2,3)))

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [7]:
# Constansts
a = tf.constant(3, shape = [2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [8]:
b = tf.constant([1,2, 3, 4, 5, 6, 7, 8], shape = [2, 4])
b

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [9]:
# Variables
a0 = tf.Variable([1, 2, 3, 4], dtype = tf.int32)
a0

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [10]:
tf.multiply(a0, b)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]], dtype=int32)>

## Basic Operations

In [11]:
a0 = tf.constant([[1, 2], [4, 5]])
b0 = tf.constant([[2, 1], [4, 3]])

tf.add(a0, b0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [8, 8]], dtype=int32)>

In [12]:
tf.multiply(a0, b0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  2],
       [16, 15]], dtype=int32)>

In [13]:
# Matrix Multiplication
tf.matmul(a0, b0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [28, 19]], dtype=int32)>

In [14]:
# Sum across entire tensor
tf.reduce_sum(a0)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [15]:
# Sum across individual tensors
tf.reduce_sum(a0, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

## Advanced Operations

In [16]:
image = tf.random.uniform([2, 2], maxval = 255, dtype = 'int32')
image

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[249, 124],
       [250,  24]], dtype=int32)>

In [17]:
new_image = tf.reshape(image, [4, 1])
new_image

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[249],
       [124],
       [250],
       [ 24]], dtype=int32)>

In [18]:
# Computing gradients: f(x) = x^2

def compute_gradient(x):
    x = tf.Variable(x, dtype = tf.float32)
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = x**2
    
    return tape.gradient(y, x).numpy()

In [19]:
compute_gradient(3)

6.0

# Linear Models

## Input Data

In [20]:
housing = pd.read_csv('/Users/Dillon/OneDrive/Documents/DataCampML/kc_house_data.csv')

In [21]:
housing_np = np.array(housing)

In [22]:
price = np.array(housing['price'], np.float32)
price

array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
      dtype=float32)

In [23]:
waterfront = tf.cast(housing['waterfront'], tf.bool)
waterfront

<tf.Tensor: shape=(21613,), dtype=bool, numpy=array([False, False, False, ..., False, False, False])>

In [24]:
beds = np.array(housing['bedrooms'])

## Loss Functions

Want to minimise loss functions. Common functions include: 
- MSE: 
    - Strongly penalises outliers
    - Large gradient near the minimum
- MAE: 
    - Scales with the size of error
    - Low gradient near minimum
- Huber:
    - Like MSE near min
    - Like MAE away from min

In [25]:
def linear_reg(intercept, slope, features):
    return intercept + features*slope

def loss_func(intercept, slope, targets, features):
    predictions = linear_reg(intercept, slope, features)
    
    return tf.keras.losses.mse(targets, predictions)

In [26]:
tf.keras.losses.mse(beds, price)

<tf.Tensor: shape=(), dtype=float32, numpy=426467460000.0>

## Linear Regression

In [27]:
price = np.array(housing['price'], np.float32)
size = np.array(housing['sqft_living'], np.float32)

intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [28]:
opt = tf.keras.optimizers.Adam()

In [29]:
for i in range(25):
    opt.minimize(lambda: loss_func(intercept, slope, price, size), var_list = [intercept, slope])
    print(loss_func(intercept, slope, price, size))

tf.Tensor(426196570000.0, shape=(), dtype=float32)
tf.Tensor(426193800000.0, shape=(), dtype=float32)
tf.Tensor(426191100000.0, shape=(), dtype=float32)
tf.Tensor(426188400000.0, shape=(), dtype=float32)
tf.Tensor(426185720000.0, shape=(), dtype=float32)
tf.Tensor(426182930000.0, shape=(), dtype=float32)
tf.Tensor(426180280000.0, shape=(), dtype=float32)
tf.Tensor(426177530000.0, shape=(), dtype=float32)
tf.Tensor(426174800000.0, shape=(), dtype=float32)
tf.Tensor(426172060000.0, shape=(), dtype=float32)
tf.Tensor(426169340000.0, shape=(), dtype=float32)
tf.Tensor(426166600000.0, shape=(), dtype=float32)
tf.Tensor(426163930000.0, shape=(), dtype=float32)
tf.Tensor(426161180000.0, shape=(), dtype=float32)
tf.Tensor(426158520000.0, shape=(), dtype=float32)
tf.Tensor(426155740000.0, shape=(), dtype=float32)
tf.Tensor(426153050000.0, shape=(), dtype=float32)
tf.Tensor(426150360000.0, shape=(), dtype=float32)
tf.Tensor(426147600000.0, shape=(), dtype=float32)
tf.Tensor(426144800000.0, shape

In [30]:
intercept.numpy()

0.124999814

In [31]:
slope.numpy()

0.124999814

## Batch Training

When dealing with large datasets it's computationally efficient to train in batches. Each batch is an epoch. 

In [32]:
path = '/Users/Dillon/OneDrive/Documents/DataCampML/kc_house_data.csv'
for batch in pd.read_csv(path, chunksize = 100):
    price = np.array(batch['price'], np.float32)
    size = np.array(batch['sqft_living'], np.float32)
    
    opt.minimize(lambda: loss_func(intercept, slope, price, size), var_list = [intercept, slope])
    
print(intercept.numpy(), slope.numpy())

0.34251952 0.34098136


# Neural Networks

## Dense Layers

In [33]:
credit = pd.read_csv('/Users/Dillon/OneDrive/Documents/DataCampML/uci_credit_card.csv')
credit_np = np.array(credit)

In [34]:
credit.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [35]:
borrower_features = np.array(credit.iloc[:,:-1], np.float32)
target = np.array(credit.iloc[:,-1], np.float32)

In [36]:
inputs = tf.constant([[1, 35]], dtype = np.float32)
weights = tf.Variable([[-0.05], [-0.01]])
bias = tf.Variable([0.5])

In [37]:
product = tf.matmul(inputs, weights)

In [38]:
dense = tf.keras.activations.sigmoid(product + bias)

In [39]:
dense

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5249792]], dtype=float32)>

In [40]:
inputs = tf.constant(credit_np, tf.float32)

In [41]:
dense1 = tf.keras.layers.Dense(10, activation = 'sigmoid')(inputs)
dense1

<tf.Tensor: shape=(30000, 10), dtype=float32, numpy=
array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.]], dtype=float32)>

In [42]:
dense2 = tf.keras.layers.Dense(5, activation = 'sigmoid')(dense1)
dense2

<tf.Tensor: shape=(30000, 5), dtype=float32, numpy=
array([[0.51939136, 0.60455966, 0.30084854, 0.6305108 , 0.5641761 ],
       [0.5040251 , 0.45684496, 0.43953142, 0.6292735 , 0.6011946 ],
       [0.51939136, 0.60455966, 0.30084854, 0.6305108 , 0.5641761 ],
       ...,
       [0.54599684, 0.40472704, 0.63580036, 0.35556877, 0.52255404],
       [0.34972095, 0.5275881 , 0.8745587 , 0.5989674 , 0.8023456 ],
       [0.37184525, 0.63709056, 0.83520615, 0.5717506 , 0.6543141 ]],
      dtype=float32)>

In [43]:
dense3 = tf.keras.layers.Dense(1, activation = 'relu')(dense2)
dense3

<tf.Tensor: shape=(30000, 1), dtype=float32, numpy=
array([[0.4979541 ],
       [0.30369034],
       [0.4979541 ],
       ...,
       [0.05963666],
       [0.        ],
       [0.01651354]], dtype=float32)>

## Activation Functions

In [44]:
inputs = borrower_features
dense1 = tf.keras.layers.Dense(100, 'relu')(inputs)
dense2 = tf.keras.layers.Dense(70, 'relu')(dense1)
dense3 = tf.keras.layers.Dense(25, 'relu')(dense2)
dense4 = tf.keras.layers.Dense(5, 'relu')(dense3)
output = tf.keras.layers.Dense(1, 'sigmoid')(dense4)

target[:5] - output.numpy()[:5]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]], dtype=float32)

## Optimizers

In [45]:
def model(bias, weights, features = borrower_features):
    product = tf.matmul(features, weights)
    z = product + bias
    return tf.keras.activations.sigmoid(z)

def loss(bias, weights, targets = target, features = borrower_features):
    predictions = model(bias, weights)
    return tf.keras.losses.binary_crossentropy(targets, predictions)

In [46]:
weights = tf.Variable(tf.random.normal([24, 7]), np.float32)
bias = tf.Variable(tf.ones([7]))

## Neural Networks

In [86]:
sign = pd.read_csv('/Users/Dillon/OneDrive/Documents/DataCampML/slmnist.csv')
X = sign.iloc[:, 1:]
y = sign.iloc[:,0]
sign_np = np.array(sign)

In [87]:
sign.head(10)

1  142  143  146  148  149  149.1  149.2  150  151  ...  0.1   15   55  \
0  0  141  142  144  145  147    149    150  151  152  ...  173  179  179   
1  1  156  157  160  162  164    166    169  171  171  ...  181  197  195   
2  3   63   26   65   86   97    106    117  123  128  ...  175  179  180   
3  1  156  160  164  168  172    175    178  180  182  ...  108  107  106   
4  0  159  163  167  168  170    173    175  178  178  ...  173  233  235   
5  3  109  119  129  134  136    142    147  151  154  ...  107  102  103   
6  0  161  164  166  171  174    175    177  178  180  ...  241  241  241   
7  1  162  164  167  169  170    171    172  173  172  ...   82  109  108   
8  1  145  148  150  152  155    157    159  161  162  ...  183  184  183   
9  1  145  146  147  147  146    146    145  146  147  ...    5  148  191   

    63  37.2  61.1  77.2  65.1  38.1   23  
0  180   181   181   182   182   183  183  
1  193   193   191   192   198   193  182  
2  182   183   183   184   185   185  185  
3  110   111   108   108   102    84   70  
4  235   236   235   235   236   235  235  
5  102    99   151   229   199   198  210  
6  241   241   242   240   240   240  240  
7  114   125   137   153   166   176  170  
8  184   189   189   180   173   168  159  
9  181   183   181   177   175   175  174  

[10 rows x 785 columns]

In [88]:
X = np.array(X)
y = np.array(y)

In [121]:
y.shape

(1999,)

In [123]:
labels = np.zeros(shape = (1999, 4))
for i in range(len(y)): 
    for j in labels[i]:
        labels[i][y[i]] = 1

In [134]:
model = tf.keras.Sequential()

In [135]:
model.add(tf.keras.layers.Dense(16, activation = 'relu', input_shape = (784,)))
model.add(tf.keras.layers.Dense(8, activation = 'relu'))
model.add(tf.keras.layers.Dense(4, activation = 'softmax'))

In [136]:
model.compile('RMSprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [137]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_27 (Dense)             (None, 16)                12560     
_________________________________________________________________
dense_28 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_29 (Dense)             (None, 4)                 36        
Total params: 12,732
Trainable params: 12,732
Non-trainable params: 0
_________________________________________________________________


## Training and Validating

In [146]:
features_train = X[:1500,:]
features_test = X[1500:,:]

labels_train = labels[:1500,:]
labels_test = labels[1500:,:]

In [147]:
model.fit(features_train, labels_train, epochs = 5, validation_split = 0.1)

Epoch 1/5
43/43 [==============================] - 0s 1ms/step - loss: 1.3864 - accuracy: 0.2541 - val_loss: 1.3874 - val_accuracy: 0.2067
Epoch 2/5
43/43 [==============================] - 0s 938us/step - loss: 1.3862 - accuracy: 0.2541 - val_loss: 1.3868 - val_accuracy: 0.2067
Epoch 3/5
43/43 [==============================] - 0s 925us/step - loss: 1.3862 - accuracy: 0.2541 - val_loss: 1.3866 - val_accuracy: 0.2067
Epoch 4/5
43/43 [==============================] - 0s 919us/step - loss: 1.3861 - accuracy: 0.2541 - val_loss: 1.3864 - val_accuracy: 0.2067
Epoch 5/5
43/43 [==============================] - 0s 919us/step - loss: 1.3860 - accuracy: 0.2541 - val_loss: 1.3862 - val_accuracy: 0.2067


In [148]:
model.evaluate(features_train, labels_train)

47/47 [==============================] - 0s 378us/step - loss: 1.3859 - accuracy: 0.2493


[1.3858940601348877, 0.24933333694934845]

In [149]:
model.evaluate(features_test, labels_test)

16/16 [==============================] - 0s 571us/step - loss: 1.3884 - accuracy: 0.2525


[1.3883559703826904, 0.25250500440597534]

## Estimator API

Much less flexible, uses best practice.